### ISSUE TITLE
Europass Plugin not working in Mahara 15.04.1 

### ISSUE THREAD

**Issue by agwells** [povsod/mahara-artefact-europass#1]
Hi Gregor,
Peter Groißböck reported over on the Mahara Launchpad, that the Europass plugin isn't working in Mahara 15.04.1: https://bugs.launchpad.net/mahara/+bug/1462945

Hi!
Europass Plugin isn't working anymore in 15.04.1.
You can't see Europass in "content" and if you have used Europass in a Mahara view, it is empty.
Firefox 38.0.1

**Comment by anzeljg** [comment]
Tested everything several times in Google Chrome (44.0) and Mozilla Firefox (39.0) and everything seems to be working OK. During the testing I've discovered some minor issues and fixed them.

I would need additional (detailed) information what does not work. Currently I'm closing this issue.
