### ISSUE TITLE
Adding a B driving licence fails and corrupts europass on 18.10

### ISSUE THREAD

**Issue by aspark21** [povsod/mahara-artefact-europass#10]
Adding a B driving licence fails and corrupts europass on 18.10

[WAR] 98 (lib/errors.php:535) [ArgumentCountError]: Too few arguments to function ArtefactTypeDrivinglicence::render_self(), 0 passed in /path/to/mahara/htdocs/artefact/europass/lib.php on line 1956 and exactly 1 expected

Call stack (most recent first):
exception(object(ArgumentCountError)) at Unknown:0

**Comment by anzeljg** [comment]
This issue was common to several elements, nit just driving licence. The problem was that the core Mahara function render_self() argumnents were changed. This is resolved.
