### ISSUE TITLE
Problem when sharing a resume

### ISSUE THREAD

**Issue by ycordel-ul** [povsod/mahara-artefact-europass#12]
Hello, 

I use Mahara 19.04.3 with the last Europass version (2019030100).

My problem looks like #5 issue but it doesn't fix the issue.

When I insert my resume into a page and want to share that page with another user, that user can see my page but the information that is displayed is his or her own.

For example, i share a page with my identity. The user who can display my page see his identity.

In addition, if i share my page with a secret url, people who visit this url have this error message :  
`Mahara: Site unavailable 
A nonrecoverable error occurred. This probably means you have encountered a bug in the system`

To reproduce this problem : 

1. Create a new page and insert your resume
2. Share this page with a registered user
3. Connect to this page with this registerd user
4. Share your page with secret url
5. Connect to this page with the secret url in private mode

Is there a fix to solve this problem?
Best regards,
Yan

**Comment by anzeljg** [comment]
Hi Yan.

I thought I updated the code here on GitHub, but apparently did only update my server. I am sorry.

Could you please test if latest commit (https://github.com/povsod/mahara-artefact-europass/commit/3d5c33a876ef4b2ef5ea38eaa3977642b071c592) works for you?

Regards,
Gregor

**Comment by ycordel-ul** [comment]
Hi Gregor, 

Thank you for you quick answer!
I have just tested the new version and your last commit solve all problems.

Best regards,
Yan

**Comment by anzeljg** [comment]
Glad to hear that!
