### ISSUE TITLE
Missing Language Files in artefact/europass/lang

### ISSUE THREAD

**Issue by mppg99** [povsod/mahara-artefact-europass#2]
Hello Gregor,

we just updated to the current version of Europass plug-in and figured out that all languages except en.utf8 in artefact/europass/lang folder are missing.
We just copied the missing languages from an older version of the plug-in but nevertheless I think this issues should be fixed cause it leads to a fatal error.

BR,
Manuel

**Comment by anzeljg** [comment]
Thank you for the info. I've noted that and will fix that issue in next update of the plugin. Does the plugin work for you? I've got noted that plugin does not work under 15.04.x (see: https://github.com/anzeljg/mahara-artefact-europass/issues/1).

**Comment by mppg99** [comment]
The plug-in is working fine after copying the missing lang-files.
We are using 15.04.2 and couldn't detect any further problems.

**Comment by anzeljg** [comment]
Thank you for the info...

**Comment by anzeljg** [comment]
Added missing language strings.
